<?php
/**
 * @package    AL_CustomSmtp
 * @copyright  Copyright (c) 2015 Arnaud Ligny
 * @author     Arnaud Ligny <arnaud@ligny.org>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script type="text/javascript">
    //<![CDATA[
    function showMessage(txt, type) {
        var html = '<ul class="messages"><li class="'+type+'-msg"><ul><li>' + txt + '</li></ul></li></ul>';
        $('test-messages').update(html);
    }
    function test() {
        new Ajax.Request('<?php echo $this->getAjaxTestUrl() ?>', {
            method: 'get',
            onSuccess: function(transport){
                if (transport.responseJSON){
                    var json = transport.responseJSON;
                    showMessage(json.message, json.status);
                }
            }
        });
    }
    //]]>
</script>
<?php echo $this->getButtonHtml() ?><div id="test-messages"></div>